# Generated by Django 4.2 on 2025-06-02 20:06

from django.db import migrations, models
import event.storage


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0022_organisation_content_event_type_content_publisher_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                storage=event.storage.MinioMediaStorage(),
                upload_to="organisation_images",
            ),
        ),
    ]
