# Generated by Django 4.2 on 2025-06-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0024_review_review_event_revie_content_f5ed2e_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Оценка от 0 до 5", verbose_name="Оценка"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="event.content",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="event.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["content"], name="event_ratin_content_3e2f73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["user"], name="event_ratin_user_id_aab6d6_idx"),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "content"], name="event_ratin_user_id_d3d441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["-created"], name="event_ratin_created_275463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["rating"], name="event_ratin_rating_142f6c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "content")},
        ),
    ]
