# Generated by Django 4.2 on 2025-06-21 13:54

from django.db import migrations, models
import django.db.models.deletion
import event.storage


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0025_rating_rating_event_ratin_content_3e2f73_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["date_start"],
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "Лайк", "verbose_name_plural": "Лайки"},
        ),
        migrations.AlterModelOptions(
            name="macrocategory",
            options={
                "verbose_name": "Макрокатегория",
                "verbose_name_plural": "Макрокатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AlterModelOptions(
            name="removedfavorite",
            options={
                "verbose_name": "Удаленное из избранного",
                "verbose_name_plural": "Удаленное из избранного",
            },
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="usercategorypreference",
            options={
                "verbose_name": "Предпочтение пользователя",
                "verbose_name_plural": "Предпочтения пользователей",
            },
        ),
        migrations.AlterField(
            model_name="content",
            name="city",
            field=models.CharField(
                choices=[
                    ("spb", "Санкт-Петербург"),
                    ("msk", "Москва"),
                    ("ekb", "Екатеринбург"),
                    ("nsk", "Новосибирск"),
                    ("nn", "Нижний Новгород"),
                ],
                default="nn",
                max_length=50,
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="contact",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Контакты"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="cost",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Стоимость"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="content",
            name="date_end",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="date_start",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="content",
            name="event_type",
            field=models.CharField(
                choices=[("online", "Онлайн"), ("offline", "Оффлайн")],
                default="offline",
                max_length=10,
                verbose_name="Тип мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to="images",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="location",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=250,
                null=True,
                verbose_name="Место проведения",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="content",
            name="publisher_id",
            field=models.IntegerField(default=1000000, verbose_name="ID издателя"),
        ),
        migrations.AlterField(
            model_name="content",
            name="publisher_type",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("organisation", "Организация")],
                default="user",
                max_length=20,
                verbose_name="Тип издателя",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="tags",
            field=models.ManyToManyField(
                related_name="contents", to="event.tags", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="time",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=250,
                null=True,
                verbose_name="Время",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="unique_id",
            field=models.CharField(
                editable=False,
                max_length=250,
                unique=True,
                verbose_name="Уникальный ID",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="event.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="event.content",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="like",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="event.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="value",
            field=models.BooleanField(verbose_name="Значение лайка"),
        ),
        migrations.AlterField(
            model_name="macrocategory",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="macrocategory",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to="images_macrocategory",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="macrocategory",
            name="name",
            field=models.CharField(
                db_index=True, max_length=250, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                storage=event.storage.MinioMediaStorage(),
                upload_to="organisation_images",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="password",
            field=models.CharField(max_length=250, verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisations",
                to="event.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="removedfavorite",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.content",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="removedfavorite",
            name="removed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата удаления"),
        ),
        migrations.AlterField(
            model_name="removedfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="event.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="tags",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="tags",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="tags",
            name="macro_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="event.macrocategory",
                verbose_name="Макрокатегория",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(
                db_index=True, max_length=250, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                choices=[
                    ("spb", "Санкт-Петербург"),
                    ("msk", "Москва"),
                    ("ekb", "Екатеринбург"),
                    ("nsk", "Новосибирск"),
                    ("nn", "Нижний Новгород"),
                ],
                default="nn",
                max_length=50,
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, max_length=250, verbose_name="Имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="usercategorypreference",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_preferences",
                to="event.tags",
                verbose_name="Тег",
            ),
        ),
        migrations.AlterField(
            model_name="usercategorypreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_preferences",
                to="event.user",
                verbose_name="Пользователь",
            ),
        ),
    ]
