# Generated by Django 4.2 on 2025-06-22 20:16

from django.db import migrations, models
import django.db.models.deletion
import event.storage


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0026_alter_content_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название маршрута"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("duration_km", models.FloatField(verbose_name="Протяжённость (км)")),
                ("duration_hours", models.FloatField(verbose_name="Время (часы)")),
                ("map_link", models.URLField(verbose_name="Ссылка на карты")),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("spb", "Санкт-Петербург"),
                            ("msk", "Москва"),
                            ("ekb", "Екатеринбург"),
                            ("nsk", "Новосибирск"),
                            ("nn", "Нижний Новгород"),
                        ],
                        default="nn",
                        max_length=50,
                        verbose_name="Город",
                    ),
                ),
                (
                    "places",
                    models.ManyToManyField(
                        limit_choices_to={"tags__macro_category__name": "places"},
                        related_name="routes",
                        to="event.content",
                        verbose_name="Места",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        limit_choices_to={"macro_category__name": "маршрут"},
                        related_name="routes",
                        to="event.tags",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршруты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoutePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        storage=event.storage.MinioMediaStorage(),
                        upload_to="route_images",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Описание фото",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="event.route",
                        verbose_name="Маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография маршрута",
                "verbose_name_plural": "Фотографии маршрутов",
                "ordering": ["order", "created"],
            },
        ),
    ]
