# Generated by Django 4.2 on 2025-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0027_route_routephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="duration_hours",
            field=models.CharField(max_length=50, verbose_name="Время (часы)"),
        ),
        migrations.AlterField(
            model_name="route",
            name="duration_km",
            field=models.CharField(max_length=50, verbose_name="Протяжённость (км)"),
        ),
    ]
