# Generated by Django 4.2 on 2025-06-23 12:28

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0028_alter_route_duration_hours_alter_route_duration_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("event.content",),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("event.content",),
        ),
        migrations.AlterField(
            model_name="content",
            name="contact",
            field=models.JSONField(
                blank=True,
                default=event.models.default_contact,
                null=True,
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="unique_id",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Уникальный ID"
            ),
        ),
    ]
