# Generated by Django 4.2 on 2025-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0029_event_place_alter_content_contact_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["name", "date_start", "location"],
                name="event_conte_name_1221bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["name"], name="name_idx"),
        ),
    ]
