version: "3.4"

services:
  minio:
    image: minio/minio:RELEASE.2024-06-06T09-36-42Z
    hostname: "minio"
    volumes:
      - minio_data:/minio_files:Z
    env_file:
      - environments/minio.env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  create_buckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - environments/minio.env
    entrypoint: "bash -c \"/usr/bin/mc config host add myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_USER}; /usr/bin/mc mb --quiet myminio/$${MINIO_BUCKET_NAME}; /usr/bin/mc anonymous set public myminio/$${MINIO_BUCKET_NAME}\""

volumes:
  minio_data:


networks:
  default:
    external:
      name: afisha
